/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<models.tables.records.ArticlesRecord, java.lang.Integer> IDENTITY_ARTICLES = Identities0.IDENTITY_ARTICLES;
	public static final org.jooq.Identity<models.tables.records.EmployeesRecord, java.lang.Integer> IDENTITY_EMPLOYEES = Identities0.IDENTITY_EMPLOYEES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<models.tables.records.ArticlesRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
	public static final org.jooq.UniqueKey<models.tables.records.EmployeesRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<models.tables.records.ArticlesRecord, java.lang.Integer> IDENTITY_ARTICLES = createIdentity(models.tables.Articles.ARTICLES, models.tables.Articles.ARTICLES.ID);
		public static org.jooq.Identity<models.tables.records.EmployeesRecord, java.lang.Integer> IDENTITY_EMPLOYEES = createIdentity(models.tables.Employees.EMPLOYEES, models.tables.Employees.EMPLOYEES.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<models.tables.records.ArticlesRecord> CONSTRAINT_E = createUniqueKey(models.tables.Articles.ARTICLES, models.tables.Articles.ARTICLES.ID);
		public static final org.jooq.UniqueKey<models.tables.records.EmployeesRecord> CONSTRAINT_4 = createUniqueKey(models.tables.Employees.EMPLOYEES, models.tables.Employees.EMPLOYEES.ID);
	}
}
