/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_08F4308C_F6F4_4D65_8C98_4E9C5E762F81</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_08F4308C_F6F4_4D65_8C98_4E9C5E762F81 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_08F4308C_F6F4_4D65_8C98_4E9C5E762F81", models.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_8E96DD6F_B426_40FA_A805_7D4A73658D61</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_8E96DD6F_B426_40FA_A805_7D4A73658D61 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_8E96DD6F_B426_40FA_A805_7D4A73658D61", models.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
