/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.ARTICLES
	 */
	public static final models.tables.Articles ARTICLES = models.tables.Articles.ARTICLES;

	/**
	 * The table PUBLIC.EMPLOYEES
	 */
	public static final models.tables.Employees EMPLOYEES = models.tables.Employees.EMPLOYEES;
}
